### PR TITLE
updated footnotes

### PR DESCRIPTION
**Pull request by jdbrown-USGS**
fixes usgs/earthquake-usdesign#113

- Updated footnotes

### CODE REVIEW

**Comment by emartinez-usgs** [comment]
Putting a `<br/>` in a list is not valid. I suggest adding a class to the subsequent `<li class="sectioning">` that gets a `.sectioning {margin-top: 1em;}` style in CSS.

**Comment by jdbrown-USGS** [comment]
Removed br tag and updated styles to created spacing in foot notes

**Comment by emartinez-usgs** [comment]
Change "values" to "value" on the following bullet points:
- Fa table footnote 4
- Fpga table footnote 2

This makes the phrasing consistent across similar notes.

**Comment by jdbrown-USGS** [comment]
Changed values to value in footnotes.

**Comment by emartinez-usgs** [comment]
The second footnote under the Fpga table should reference "Fpga" and not "Fa".

**Comment by jdbrown-USGS** [comment]
Changed Fa to Fpga in footnote.

**Pull request merged**
