### PR TITLE
Seismicdesign 246

### PR DESCRIPTION
**Pull request by emcwhirter-usgs**

### CODE REVIEW

**Comment by emartinez-usgs** [comment]
- Do not die if fopen fails. Instead throw an exception.
- If a line is blank, throw an exception.
- fgets can return null if EOF is reached. Check for this and return null.
- no need to track lineCount
- returned object should have all `safefloatval` applied to all values.

**Comment by emartinez-usgs** [comment]
- Remove warnings parameter from nextLine method and also remove __addWarning method (it is not used).

**Comment by emartinez-usgs** [comment]
- Check if `$line === false` rather than calling `feof` otherwise we might lose the last line of data.
- Use `safefloatval` instead of `floatval`.

**Comment by emartinez-usgs** [comment]
- For `safefloatval` to work, you'll need to `include_once` the functions file.

**Comment by emartinez-usgs** [comment]
I'm not sure the include will work without some sort of path to the included file. Have you tried running any code against this class implementation?

**Comment by emcwhirter-usgs** [comment]
Yeah, my code seems to work fine. I'll be pushing that up in a couple of
minutes. Now that you mention it though, I didn't try to run against bad
files yet.

Eddie McWhirter
Systems Manager, Computer Scientist, IT Specialist
USGS Geomagnetism Program
Office: 303-273-8488
Email: emcwhirter@usgs.gov

**Pull request merged**
